### ISSUE TITLE
Data management

### ISSUE THREAD

**Issue by duncansf** [etopian/docker-wordpress#2]
Hi, 

First of all I woulld like to thank you for creating a solution that has WP + production together, making it easier for many people who are just starting out with Docker.

We're a small WordPress service provider, looking to keep things as simple and low cost as possible maybe for the first few VM's, and who wants to implement Docker. It seems hosting multiple WP sites per VM is the way to go to achieve lower cost. While we're still getting the hang of using Docker, it seems that you're solution is a good starting point as we improve our knowledge.

Based on your solution, I've got some questions around data management in production for VM's that host multiple WP sites.

1) Do you recommend having one database for all the sites on a VM or one DB per site?
2) What is your take on using Docker data volume containers to persist and manage data?
3) What is your recommendation for the best way of backing up and restoring the data using your solution? 

I've also got one or two general questions I would really like to ask related to Docker if at all possible - not sure if I should post them here?

Many thanks
Duncan

**Comment by etopian** [comment]
1. one DB per site. it makes little difference to the single instance of mysql whether you put tables in one database or multiple ones. but putting all sites in one database makes a mess of things especially if you want to recover a site that's been hacked.
2. we don't use it because it gets in the way of backup. if you mount each site from the host file system it's easier to deal with..
3. it's simply a matter of taking a database dump of all databases using mysqldump and backing up all files in the /data/sites directory on host which contains all the wp files, see 2.

**Comment by duncansf** [comment]
Thanks allot for this advice. It really does help.

1) Dev workflow for website updates: When updating a clients website based on this solution, is there a workflow that you would recommend i.e. maybe duplicate locally, update and then upload again?
2) Optimisation: Whats the best way to scale the performance of individual Docker sites, on a site-by-site basis, when using a shared VPS like we are planning to implement with this solution?

Thanks again!

**Comment by etopian** [comment]
1) you could do that or create a separate staging container for each site to test updates before you apply them.
2) use redis. instructions are on dockerwordpress.com. you can also use zen cache wp plugin.

**Comment by duncansf** [comment]
Thanks!
